defaults:
  - _self_
  - data: tcsa_polar
  - model: profiler_ir1
  - callbacks: default
  - paths: default
  - logger: wandb

seed: 42

train: true
test: true

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  max_epochs: 200
  accelerator: auto
  devices: 1
  precision: 32-true
  check_val_every_n_epoch: 10
